function [prdData, info] = predict_Nyctiphanes_australis(par, data, auxData)


% unpack par, data, auxData
cPar = parscomp_st(par); vars_pull(par); %report_animal(par);
vars_pull(cPar);  vars_pull(data);  vars_pull(auxData);

% compute temperature correction factors
TC_8   = tempcorr(temp.tMUFA_8UVL,  T_ref, T_A);
TC_12  = tempcorr(temp.tMUFA_12UVL, T_ref, T_A);
TC_13  = tempcorr(temp.tMUFA_13UVL, T_ref, T_A);
TC_16  = tempcorr(temp.tMUFA_16UVL, T_ref, T_A);
TC_19  = tempcorr(temp.tMUFA_19UVL, T_ref, T_A);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%% Prediction for changes in fatty acids and amino acids   %%%%%
%%%%%%%%%%%%          with temperature and light                     %%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

pars_uv8H  = [MC0_MUFA, JCM_MUFA,...
              MC0_PUFA, JCM_PUFA,...
              MC0_SAFA, JCM_SAFA,...
              MC0_UFA,  JCM_UFA,...
              MC0_EAA,  JCM_EAA,...
              MC0_NEAA, JCM_NEAA,...
              TC_8, mufa_UVH, pufa_UVH, safa_UVH, ufa_UVH ,eaa_UVH, neaa_UVH,...
              UV_H, p_M, mu_E]; 
[EMUFA_8UVH, EPUFA_8UVH, ESAFA_8UVH, EUFA_8UVH, EEAA_8UVH, ENEAA_8UVH] = lin_fa_5(pars_uv8H, tMUFA_8UVH,...
    tPUFA_8UVH, tSAFA_8UVH,tUFA_8UVH,tEAA_8UVH, tNEAA_8UVH);

pars_uv8L  = [MC0_MUFA, JCM_MUFA,...
              MC0_PUFA, JCM_PUFA,...
              MC0_SAFA, JCM_SAFA,...
              MC0_UFA,  JCM_UFA,...
              MC0_EAA,  JCM_EAA,...
              MC0_NEAA, JCM_NEAA,...
              TC_8, mufa_UVL, pufa_UVL, safa_UVL, ufa_UVL, eaa_UVL, neaa_UVL,...
              UV_L, p_M, mu_E];
[EMUFA_8UVL, EPUFA_8UVL, ESAFA_8UVL, EUFA_8UVL ,EEAA_8UVL, ENEAA_8UVL] = lin_fa_5(pars_uv8L, tMUFA_8UVL,...
    tPUFA_8UVL, tSAFA_8UVL, tUFA_8UVL,tEAA_8UVL, tNEAA_8UVL);

pars_uv12H  = [MC0_MUFA, JCM_MUFA,...
               MC0_PUFA, JCM_PUFA,...
               MC0_SAFA, JCM_SAFA,...
               MC0_UFA,  JCM_UFA,...
               MC0_EAA,  JCM_EAA,...
               MC0_NEAA, JCM_NEAA,...
               TC_12, mufa_UVH, pufa_UVH, safa_UVH, ufa_UVH, eaa_UVH, neaa_UVH,...
               UV_H, p_M, mu_E];
[EMUFA_12UVH, EPUFA_12UVH, ESAFA_12UVH, EUFA_12UVH,EEAA_12UVH, ENEAA_12UVH] = lin_fa_5(pars_uv12H, tMUFA_12UVH,...
    tPUFA_12UVH, tSAFA_12UVH, tUFA_12UVH, tEAA_12UVH, tNEAA_12UVH);

pars_uv12L  = [MC0_MUFA, JCM_MUFA,...
               MC0_PUFA, JCM_PUFA,...
               MC0_SAFA, JCM_SAFA,...
               MC0_UFA,  JCM_UFA,...
               MC0_EAA,  JCM_EAA,...
               MC0_NEAA, JCM_NEAA,...
               TC_12, mufa_UVL, pufa_UVL, safa_UVL, ufa_UVL, eaa_UVL, neaa_UVL,...
               UV_L, p_M, mu_E];
[EMUFA_12UVL, EPUFA_12UVL, ESAFA_12UVL, EUFA_12UVL, EEAA_12UVL, ENEAA_12UVL] = lin_fa_5(pars_uv12L, tMUFA_12UVL,...
    tPUFA_12UVL, tSAFA_12UVL, tUFA_12UVL, tEAA_12UVL, tNEAA_12UVL);

pars_uv13H  = [MC0_MUFA, JCM_MUFA,...
               MC0_PUFA, JCM_PUFA,...
               MC0_SAFA, JCM_SAFA,...
               MC0_UFA,  JCM_UFA,...
               MC0_EAA,  JCM_EAA,...
               MC0_NEAA, JCM_NEAA,...
               TC_13, mufa_UVH, pufa_UVH, safa_UVH, ufa_UVH, eaa_UVH, neaa_UVH,...
               UV_H, p_M, mu_E];
[EMUFA_13UVH, EPUFA_13UVH, ESAFA_13UVH, EUFA_13UVH, EEAA_13UVH, ENEAA_13UVH] = lin_fa_5(pars_uv13H,tMUFA_13UVH,...
    tPUFA_13UVH, tSAFA_13UVH, tUFA_13UVH, tEAA_13UVH, tNEAA_13UVH);

pars_uv13L  = [MC0_MUFA, JCM_MUFA,...
               MC0_PUFA, JCM_PUFA,...
               MC0_SAFA, JCM_SAFA,...
               MC0_UFA,  JCM_UFA,...
               MC0_EAA,  JCM_EAA,...
               MC0_NEAA, JCM_NEAA,...
               TC_13, mufa_UVL, pufa_UVL, safa_UVL, ufa_UVL, eaa_UVH, neaa_UVH,...
               UV_L, p_M, mu_E];
[EMUFA_13UVL, EPUFA_13UVL, ESAFA_13UVL, EUFA_13UVL, EEAA_13UVL, ENEAA_13UVL] = lin_fa_5(pars_uv13L,tMUFA_13UVL,...
    tPUFA_13UVL, tSAFA_13UVL, tUFA_13UVL, tEAA_13UVL, tNEAA_13UVL);

pars_uv16H  = [MC0_MUFA, JCM_MUFA,...
               MC0_PUFA, JCM_PUFA,...
               MC0_SAFA, JCM_SAFA,...
               MC0_UFA,  JCM_UFA,...
               MC0_EAA,  JCM_EAA,...
               MC0_NEAA, JCM_NEAA,...
               TC_16, mufa_UVH, pufa_UVH, safa_UVH, ufa_UVH,eaa_UVH, neaa_UVH,...
               UV_H, p_M, mu_E];
[EMUFA_16UVH, EPUFA_16UVH, ESAFA_16UVH, EUFA_16UVH, EEAA_16UVH, ENEAA_16UVH] = lin_fa_5(pars_uv16H,tMUFA_16UVH,...
    tPUFA_16UVH, tSAFA_16UVH, tUFA_16UVH, tEAA_16UVH, tNEAA_16UVL);

pars_uv16L  = [MC0_MUFA, JCM_MUFA,...
               MC0_PUFA, JCM_PUFA,...
               MC0_SAFA, JCM_SAFA,...
               MC0_UFA,  JCM_UFA,...
               MC0_EAA,  JCM_EAA,...
               MC0_NEAA, JCM_NEAA,...
               TC_16, mufa_UVL, pufa_UVL, safa_UVL, ufa_UVL, eaa_UVL, neaa_UVL,...
               UV_L, p_M, mu_E];
[EMUFA_16UVL, EPUFA_16UVL, ESAFA_16UVL, EUFA_16UVL, EEAA_16UVL, ENEAA_16UVL] = lin_fa_5(pars_uv16L,tMUFA_16UVL,...
    tPUFA_16UVL, tSAFA_16UVL, tUFA_16UVL, tEAA_16UVL, tNEAA_16UVL);

pars_uv19H  = [MC0_MUFA, JCM_MUFA,...
               MC0_PUFA, JCM_PUFA,...
               MC0_SAFA, JCM_SAFA,...
               MC0_UFA,  JCM_UFA,...
               MC0_EAA,  JCM_EAA,...
               MC0_NEAA, JCM_NEAA,...
               TC_19, mufa_PAR, pufa_UVH, safa_UVH, ufa_UVH, eaa_UVH, neaa_UVH,...
               UV_H, p_M, mu_E];
[EMUFA_19UVH, EPUFA_19UVH, ESAFA_19UVH, EUFA_19UVH, EEAA_19UVH, ENEAA_19UVH] = lin_fa_5(pars_uv19H,tMUFA_19UVH,...
    tPUFA_19UVH, tSAFA_19UVH, tUFA_19UVH, tEAA_19UVH, tNEAA_19UVH);

pars_uv19L  = [MC0_MUFA, JCM_MUFA,...
               MC0_PUFA, JCM_PUFA,...
               MC0_SAFA, JCM_SAFA,...
               MC0_UFA,  JCM_UFA,...
               MC0_EAA,  JCM_EAA,...
               MC0_NEAA, JCM_NEAA,...
               TC_19, mufa_UVL, pufa_UVL, safa_UVL, ufa_UVL,eaa_UVL, neaa_UVL,...
               UV_L, p_M, mu_E];
[EMUFA_19UVL, EPUFA_19UVL, ESAFA_19UVL, EUFA_19UVL, EEAA_19UVL, ENEAA_19UVL] = lin_fa_5(pars_uv19L,tMUFA_19UVL,...
    tPUFA_19UVL, tSAFA_19UVL, tUFA_19UVL,tEAA_19UVL, tNEAA_19UVL);

pars_par8 = [MC0_MUFA, JCM_MUFA,...
             MC0_PUFA, JCM_PUFA,...
             MC0_SAFA, JCM_SAFA,...
             MC0_UFA,  JCM_UFA,...
             MC0_EAA,  JCM_EAA,...
             MC0_NEAA, JCM_NEAA,... 
             TC_8, mufa_PAR, pufa_PAR, safa_PAR, ufa_PAR, eaa_PAR, neaa_PAR,...
             PAR_H, p_M, mu_E];
[EMUFA_8PAR,  EPUFA_8PAR,  ESAFA_8PAR, EUFA_8PAR, EEAA_8PAR, ENEAA_8PAR]  = lin_fa_5(pars_par8,tMUFA_8PAR,...
    tPUFA_8PAR, tSAFA_8PAR, tUFA_8PAR,tEAA_8PAR, tNEAA_8PAR);

pars_par12 = [MC0_MUFA, JCM_MUFA,...
              MC0_PUFA, JCM_PUFA,...
              MC0_SAFA, JCM_SAFA,...
              MC0_UFA,  JCM_UFA,...
              MC0_EAA,  JCM_EAA,...
              MC0_NEAA, JCM_NEAA,... 
              TC_12, mufa_PAR, pufa_PAR, safa_PAR, ufa_PAR, eaa_PAR, neaa_PAR,...
              PAR_H, p_M, mu_E];
[EMUFA_12PAR, EPUFA_12PAR, ESAFA_12PAR, EUFA_12PAR, EEAA_12PAR, ENEAA_12PAR] = lin_fa_5(pars_par12,tMUFA_12PAR,...
    tPUFA_12PAR, tSAFA_12PAR, tUFA_12PAR, tEAA_12PAR, tNEAA_12PAR);

pars_par13 = [MC0_MUFA, JCM_MUFA,...
              MC0_PUFA, JCM_PUFA,...
              MC0_SAFA, JCM_SAFA,...
              MC0_UFA,  JCM_UFA,...
              MC0_EAA,  JCM_EAA,...
              MC0_NEAA, JCM_NEAA...
              TC_13, mufa_PAR, pufa_PAR, safa_PAR, ufa_PAR, eaa_PAR, neaa_PAR,...
              PAR_H, p_M, mu_E];
[EMUFA_13PAR, EPUFA_13PAR, ESAFA_13PAR, EUFA_13PAR, EEAA_13PAR, ENEAA_13PAR] = lin_fa_5(pars_par13,tMUFA_13PAR,...
    tPUFA_13PAR, tSAFA_13PAR, tUFA_13PAR, tEAA_13PAR, tNEAA_13PAR);

pars_par16 = [MC0_MUFA, JCM_MUFA,...
              MC0_PUFA, JCM_PUFA,...
              MC0_SAFA, JCM_SAFA,...
              MC0_UFA,  JCM_UFA,...
              MC0_EAA,  JCM_EAA,...
              MC0_NEAA, JCM_NEAA,...
              TC_16, mufa_PAR, pufa_PAR, safa_PAR, ufa_PAR, eaa_PAR, neaa_PAR,...
              PAR_H, p_M, mu_E];
[EMUFA_16PAR, EPUFA_16PAR, ESAFA_16PAR, EUFA_16PAR,EEAA_16PAR, ENEAA_16PAR] = lin_fa_5(pars_par16,tMUFA_16PAR,...
    tPUFA_16PAR, tSAFA_16PAR, tUFA_16PAR,tEAA_16PAR, tNEAA_16PAR);
%
pars_par19 = [MC0_MUFA, JCM_MUFA,...
              MC0_PUFA, JCM_PUFA,...
              MC0_SAFA, JCM_SAFA,...
              MC0_UFA,  JCM_UFA,...
              MC0_EAA,  JCM_EAA,...
              MC0_NEAA, JCM_NEAA,...
              TC_19, mufa_PAR, pufa_PAR, safa_PAR, ufa_PAR, eaa_PAR, neaa_PAR,...
              PAR_H, p_M, mu_E];
[EMUFA_19PAR, EPUFA_19PAR, ESAFA_19PAR, EUFA_19PAR, EEAA_19PAR, ENEAA_19PAR] = lin_fa_5(pars_par19,tMUFA_19PAR,...
    tPUFA_19PAR, tSAFA_19PAR, tUFA_19PAR, tEAA_19PAR, tNEAA_19PAR);
%
% pack to output
info = 1;
prdData.tMUFA_8UVL  = EMUFA_8UVL;
prdData.tMUFA_8UVH  = EMUFA_8UVH;
prdData.tPUFA_8UVL  = EPUFA_8UVL;
prdData.tPUFA_8UVH  = EPUFA_8UVH;
prdData.tSAFA_8UVL  = ESAFA_8UVL;
prdData.tSAFA_8UVH  = ESAFA_8UVH;
prdData.tUFA_8UVL   = EUFA_8UVL;
prdData.tUFA_8UVH   = EUFA_8UVH;

prdData.tMUFA_12UVL  = EMUFA_12UVL;
prdData.tMUFA_12UVH  = EMUFA_12UVH;
prdData.tPUFA_12UVL  = EPUFA_12UVL;
prdData.tPUFA_12UVH  = EPUFA_12UVH;
prdData.tSAFA_12UVL  = ESAFA_12UVL;
prdData.tSAFA_12UVH  = ESAFA_12UVH;
prdData.tUFA_12UVL   = EUFA_12UVL;
prdData.tUFA_12UVH   = EUFA_12UVH;

prdData.tMUFA_13UVL  = EMUFA_13UVL;
prdData.tMUFA_13UVH  = EMUFA_13UVH;
prdData.tPUFA_13UVL  = EPUFA_13UVL;
prdData.tPUFA_13UVH  = EPUFA_13UVH;
prdData.tSAFA_13UVL  = ESAFA_13UVL;
prdData.tSAFA_13UVH  = ESAFA_13UVH;
prdData.tUFA_13UVL   = EUFA_13UVL;
prdData.tUFA_13UVH   = EUFA_13UVH;

prdData.tMUFA_16UVL  = EMUFA_16UVL;
prdData.tMUFA_16UVH  = EMUFA_16UVH;
prdData.tPUFA_16UVL  = EPUFA_16UVL;
prdData.tPUFA_16UVH  = EPUFA_16UVH;
prdData.tSAFA_16UVL  = ESAFA_16UVL;
prdData.tSAFA_16UVH  = ESAFA_16UVH;
prdData.tUFA_16UVL   = EUFA_16UVL;
prdData.tUFA_16UVH   = EUFA_16UVH;

prdData.tMUFA_19UVL  = EMUFA_19UVL;
prdData.tMUFA_19UVH  = EMUFA_19UVH;
prdData.tPUFA_19UVL  = EPUFA_19UVL;
prdData.tPUFA_19UVH  = EPUFA_19UVH;
prdData.tSAFA_19UVL  = ESAFA_19UVL;
prdData.tSAFA_19UVH  = ESAFA_19UVH;
prdData.tUFA_19UVL   = EUFA_19UVL;
prdData.tUFA_19UVH   = EUFA_19UVH;

prdData.tMUFA_8PAR   = EMUFA_8PAR;
prdData.tPUFA_8PAR   = EPUFA_8PAR;
prdData.tSAFA_8PAR   = ESAFA_8PAR;
prdData.tUFA_8PAR   = EUFA_8PAR;

prdData.tMUFA_12PAR  = EMUFA_12PAR;
prdData.tPUFA_12PAR  = EPUFA_12PAR;
prdData.tSAFA_12PAR  = ESAFA_12PAR;
prdData.tUFA_12PAR   = EUFA_12PAR;

prdData.tMUFA_13PAR  = EMUFA_13PAR;
prdData.tPUFA_13PAR  = EPUFA_13PAR;
prdData.tSAFA_13PAR  = ESAFA_13PAR;
prdData.tUFA_13PAR   = EUFA_13PAR;

prdData.tMUFA_16PAR  = EMUFA_16PAR;
prdData.tPUFA_16PAR  = EPUFA_16PAR;
prdData.tSAFA_16PAR  = ESAFA_16PAR;
prdData.tUFA_16PAR   = EUFA_16PAR;

prdData.tMUFA_19PAR  = EMUFA_19PAR;
prdData.tPUFA_19PAR  = EPUFA_19PAR;
prdData.tSAFA_19PAR  = ESAFA_19PAR;
prdData.tUFA_19PAR   = EUFA_19PAR;

prdData.tEAA_8UVH  = EEAA_8UVH;
prdData.tNEAA_8UVH = ENEAA_8UVH;
prdData.tEAA_8UVL  = EEAA_8UVL;
prdData.tNEAA_8UVL = ENEAA_8UVL;

prdData.tEAA_12UVH  = EEAA_12UVH;
prdData.tNEAA_12UVH = ENEAA_12UVH;
prdData.tEAA_12UVL  = EEAA_12UVL;
prdData.tNEAA_12UVL = ENEAA_12UVL;

prdData.tEAA_13UVH  = EEAA_13UVH;
prdData.tNEAA_13UVH = ENEAA_13UVH;
prdData.tEAA_13UVL  = EEAA_13UVL;
prdData.tNEAA_13UVL = ENEAA_13UVL;

prdData.tEAA_16UVH  = EEAA_16UVH;
prdData.tNEAA_16UVH = ENEAA_16UVH;
prdData.tEAA_16UVL  = EEAA_16UVL;
prdData.tNEAA_16UVL = ENEAA_16UVL;

prdData.tEAA_19UVH  = EEAA_19UVH;
prdData.tNEAA_19UVH = ENEAA_19UVH;
prdData.tEAA_19UVL  = EEAA_19UVL;
prdData.tNEAA_19UVL = ENEAA_19UVL;

prdData.tEAA_8PAR   = EEAA_8PAR;
prdData.tNEAA_8PAR  = ENEAA_8PAR;
prdData.tEAA_12PAR  = EEAA_12PAR;
prdData.tNEAA_12PAR = ENEAA_12PAR;
prdData.tEAA_13PAR  = EEAA_13PAR;
prdData.tNEAA_13PAR = ENEAA_13PAR;
prdData.tEAA_16PAR  = EEAA_16PAR;
prdData.tNEAA_16PAR = ENEAA_16PAR;
prdData.tEAA_19PAR  = EEAA_19PAR;
prdData.tNEAA_19PAR = ENEAA_19PAR;

end



